import {
  Waves, Dumbbell, Car, Shield, UtensilsCrossed, TreePine,
  ShoppingBag, Ship, School, Heart, Dog, Baby, Coffee,
  Plane, Bus, Train, Bike, Gamepad2, Tv, Wifi, Sparkles,
  Bath, Bed, Sofa, Flower2, Mountain, Sunset, Anchor,
  HelpCircle,
} from "lucide-react";

const amenityMap: Record<string, React.ElementType> = {
  "beach access": Waves,
  "swimming pool": Waves,
  "pool": Waves,
  "gym": Dumbbell,
  "fitness": Dumbbell,
  "parking": Car,
  "private parking": Car,
  "24/7 security": Shield,
  "security": Shield,
  "concierge": Sparkles,
  "fine dining": UtensilsCrossed,
  "restaurant": UtensilsCrossed,
  "spa": Heart,
  "yacht club": Anchor,
  "marina": Ship,
  "garden": TreePine,
  "park": TreePine,
  "play area": Gamepad2,
  "kids play area": Baby,
  "school": School,
  "retail": ShoppingBag,
  "shops": ShoppingBag,
  "pet friendly": Dog,
  "cafe": Coffee,
  "jogging track": Bike,
  "cycling": Bike,
  "wifi": Wifi,
  "smart home": Tv,
  "elevator": Mountain,
  "barbecue area": Flower2,
  "bbq": Flower2,
  "sauna": Bath,
  "steam room": Bath,
  "business center": Sofa,
  "rooftop terrace": Sunset,
  "tennis court": Gamepad2,
  "basketball court": Gamepad2,
  "volleyball": Gamepad2,
  "cinema": Tv,
  "theater": Tv,
  "yoga": Heart,
  "meditation": Heart,
  "golf course": TreePine,
  "mini golf": TreePine,
  "water park": Waves,
  "lagoon": Waves,
  "canal": Ship,
  "lake": Waves,
  "walking trails": TreePine,
  "outdoor cinema": Tv,
  "club house": Sofa,
  "community center": Sofa,
  "pharmacy": Heart,
  "clinic": Heart,
  "mosque": Mountain,
  "chapel": Mountain,
};

export function AmenityIcon({ name }: { name: string }) {
  const key = name.toLowerCase();
  const Icon = amenityMap[key] || HelpCircle;
  return <Icon className="w-5 h-5 text-navy-800" />;
}
